config/routes.rb
Rails.application.routes.draw do
  resources :jobs 
  root 'jobs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]

	def index
		if params[:category].blank?
			@jobs = Job.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@jobs = Job.where(category_id: @category_id).order("created_at DESC")
		end
	end

	def show
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.new(jobs_params)

		if @job.save
			redirect_to @job
		else
			render "New"
		end
	end

	def edit
	end

	def update
		if @job.update(jobs_params)
			redirect_to @job
		else
			render "Edit"
		end
	end

	def destroy
		@job.destroy
		redirect_to root_path
	end

	private

	def jobs_params
		params.require(:job).permit(:title, :school, :salary, :description,)
	end

	def find_job
		@job = Job.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
.container 
  = simple_form_for(@job, html: { class: 'form-horizontal'}) do |f|
    .form-group
      = f.input :title, label:  "Job Title"
    .form-group
      = f.input :school, label:  "School"
    .form-group
      = f.input :salary, label:  "Salary"
    .form-group
      = f.input :description, label: "Job Description"

    =f.button :submit

app/views/jobs/edit.html.haml
%h1 Edit Job

= render 'form'

= link_to "Back", root_path

app/views/jobs/index.html.haml
- @jobs.each do |job|
  %h2= link_to job.title, job
  %p= job.school
  %p= job.salary
  %p= job.description

= link_to "New Job", new_job_path

app/views/jobs/new.html.haml
%h1 Create A Job

= render 'form'

= link_to "Back", root_path

app/views/jobs/show.html.haml
%h1= @job.title
%p= @job.school
%p= @job.salary
%p= @job.description

= link_to "Home", root_path, class: "btn btn-sm btn-default"

= link_to "New Job", new_job_path, class: "btn btn-sm btn-default"

= link_to "Edit", edit_job_path(@job), class: "btn btn-sm btn-default"

= link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are you sure you want to delete this job posting?" }, class: "btn btn-sm btn-default"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>